export const AUTH_ACTIONS = {
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  REFRESH_SUCCESS: 'AUTH_REFRESH_SUCCESS',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  LOGOUT: 'AUTH_LOGOUT',
  LOGOUT_ALL: 'AUTH_LOGOUT_ALL',
} as const

export const AUTH_ROLE_NAMES = {
  ADMIN: 'Admin',
  LECTURER: 'Giảng viên',
  ADVISOR: 'Cố vấn',
  STUDENT: 'Sinh viên',
} as const
